// Colors.js Matugen Colors for quickshell

var darkColors = {
    "background": "#091615",
    "error": "#ffb4ab",
    "error-container": "#93000a",
    "inverse-on-surface": "#263332",
    "inverse-primary": "#006a67",
    "inverse-surface": "#d7e5e4",
    "on-background": "#d7e5e4",
    "on-error": "#690005",
    "on-error-container": "#ffdad6",
    "on-primary": "#003735",
    "on-primary-container": "#00fcf6",
    "on-primary-fixed": "#00201f",
    "on-primary-fixed-variant": "#00504e",
    "on-secondary": "#00363e",
    "on-secondary-container": "#bdeaf4",
    "on-secondary-fixed": "#001f24",
    "on-secondary-fixed-variant": "#1f4d55",
    "on-surface": "#d7e5e4",
    "on-surface-variant": "#bbc9c8",
    "on-tertiary": "#003546",
    "on-tertiary-container": "#bde9ff",
    "on-tertiary-fixed": "#001f2a",
    "on-tertiary-fixed-variant": "#004d64",
    "outline": "#859392",
    "outline-variant": "#3c4948",
    "primary": "#00ddd8",
    "primary-container": "#00504e",
    "primary-fixed": "#00fcf6",
    "primary-fixed-dim": "#00ddd8",
    "scrim": "#000000",
    "secondary": "#a1ced7",
    "secondary-container": "#1f4d55",
    "secondary-fixed": "#bdeaf4",
    "secondary-fixed-dim": "#a1ced7",
    "shadow": "#000000",
    "source-color": "#1bf7f1",
    "surface": "#091615",
    "surface-bright": "#2f3c3b",
    "surface-container": "#152221",
    "surface-container-high": "#1f2c2c",
    "surface-container-highest": "#2a3736",
    "surface-container-low": "#111e1d",
    "surface-container-lowest": "#041010",
    "surface-dim": "#091615",
    "surface-tint": "#00ddd8",
    "surface-variant": "#3c4948",
    "tertiary": "#95ceea",
    "tertiary-container": "#004d64",
    "tertiary-fixed": "#bde9ff",
    "tertiary-fixed-dim": "#95ceea",
}

function getDarkColors() {
    return darkColors;
}

function updateDarkColors(newDarkColors) {
    darkColors = Object.assign({}, darkColors, newDarkColors);
}

var lightColors = {
    "background": "#eefcfb",
    "error": "#ba1a1a",
    "error-container": "#ffdad6",
    "inverse-on-surface": "#e5f4f2",
    "inverse-primary": "#00ddd8",
    "inverse-surface": "#263332",
    "on-background": "#111e1d",
    "on-error": "#ffffff",
    "on-error-container": "#410002",
    "on-primary": "#ffffff",
    "on-primary-container": "#00201f",
    "on-primary-fixed": "#00201f",
    "on-primary-fixed-variant": "#00504e",
    "on-secondary": "#ffffff",
    "on-secondary-container": "#001f24",
    "on-secondary-fixed": "#001f24",
    "on-secondary-fixed-variant": "#1f4d55",
    "on-surface": "#111e1d",
    "on-surface-variant": "#3c4948",
    "on-tertiary": "#ffffff",
    "on-tertiary-container": "#001f2a",
    "on-tertiary-fixed": "#001f2a",
    "on-tertiary-fixed-variant": "#004d64",
    "outline": "#6c7a79",
    "outline-variant": "#bbc9c8",
    "primary": "#006a67",
    "primary-container": "#00fcf6",
    "primary-fixed": "#00fcf6",
    "primary-fixed-dim": "#00ddd8",
    "scrim": "#000000",
    "secondary": "#39656d",
    "secondary-container": "#bdeaf4",
    "secondary-fixed": "#bdeaf4",
    "secondary-fixed-dim": "#a1ced7",
    "shadow": "#000000",
    "source-color": "#1bf7f1",
    "surface": "#eefcfb",
    "surface-bright": "#eefcfb",
    "surface-container": "#e2f1ef",
    "surface-container-high": "#ddebe9",
    "surface-container-highest": "#d7e5e4",
    "surface-container-low": "#e8f7f5",
    "surface-container-lowest": "#ffffff",
    "surface-dim": "#cedddb",
    "surface-tint": "#006a67",
    "surface-variant": "#d7e5e4",
    "tertiary": "#27657d",
    "tertiary-container": "#bde9ff",
    "tertiary-fixed": "#bde9ff",
    "tertiary-fixed-dim": "#95ceea",
}

function getLightColors() {
    return lightColors;
}

function updateLightColors(newLightColors) {
    lightColors = Object.assign({}, lightColors, newLightColors);
}