// Colors.js Matugen Colors for quickshell

var darkColors = {
    "background": "#091517",
    "error": "#ffb4ab",
    "error-container": "#93000a",
    "inverse-on-surface": "#263334",
    "inverse-primary": "#006970",
    "inverse-surface": "#d7e5e6",
    "on-background": "#d7e5e6",
    "on-error": "#690005",
    "on-error-container": "#ffdad6",
    "on-primary": "#00363a",
    "on-primary-container": "#7df4ff",
    "on-primary-fixed": "#002022",
    "on-primary-fixed-variant": "#004f54",
    "on-secondary": "#053542",
    "on-secondary-container": "#c0e9f9",
    "on-secondary-fixed": "#001f28",
    "on-secondary-fixed-variant": "#234c59",
    "on-surface": "#d7e5e6",
    "on-surface-variant": "#bbc9ca",
    "on-tertiary": "#00344d",
    "on-tertiary-container": "#c8e6ff",
    "on-tertiary-fixed": "#001e2e",
    "on-tertiary-fixed-variant": "#124b69",
    "outline": "#869395",
    "outline-variant": "#3c494a",
    "primary": "#00dbe9",
    "primary-container": "#004f54",
    "primary-fixed": "#7df4ff",
    "primary-fixed-dim": "#00dbe9",
    "scrim": "#000000",
    "secondary": "#a4cddd",
    "secondary-container": "#234c59",
    "secondary-fixed": "#c0e9f9",
    "secondary-fixed-dim": "#a4cddd",
    "shadow": "#000000",
    "source-color": "#273132",
    "surface": "#091517",
    "surface-bright": "#2f3b3d",
    "surface-container": "#152223",
    "surface-container-high": "#202c2d",
    "surface-container-highest": "#2a3738",
    "surface-container-low": "#111e1f",
    "surface-container-lowest": "#041011",
    "surface-dim": "#091517",
    "surface-tint": "#00dbe9",
    "surface-variant": "#3c494a",
    "tertiary": "#9cccf0",
    "tertiary-container": "#124b69",
    "tertiary-fixed": "#c8e6ff",
    "tertiary-fixed-dim": "#9cccf0",
}

function getDarkColors() {
    return darkColors;
}

function updateDarkColors(newDarkColors) {
    darkColors = Object.assign({}, darkColors, newDarkColors);
}

var lightColors = {
    "background": "#eefcfd",
    "error": "#ba1a1a",
    "error-container": "#ffdad6",
    "inverse-on-surface": "#e5f3f5",
    "inverse-primary": "#00dbe9",
    "inverse-surface": "#263334",
    "on-background": "#111e1f",
    "on-error": "#ffffff",
    "on-error-container": "#410002",
    "on-primary": "#ffffff",
    "on-primary-container": "#002022",
    "on-primary-fixed": "#002022",
    "on-primary-fixed-variant": "#004f54",
    "on-secondary": "#ffffff",
    "on-secondary-container": "#001f28",
    "on-secondary-fixed": "#001f28",
    "on-secondary-fixed-variant": "#234c59",
    "on-surface": "#111e1f",
    "on-surface-variant": "#3c494a",
    "on-tertiary": "#ffffff",
    "on-tertiary-container": "#001e2e",
    "on-tertiary-fixed": "#001e2e",
    "on-tertiary-fixed-variant": "#124b69",
    "outline": "#6c7a7b",
    "outline-variant": "#bbc9ca",
    "primary": "#006970",
    "primary-container": "#7df4ff",
    "primary-fixed": "#7df4ff",
    "primary-fixed-dim": "#00dbe9",
    "scrim": "#000000",
    "secondary": "#3c6472",
    "secondary-container": "#c0e9f9",
    "secondary-fixed": "#c0e9f9",
    "secondary-fixed-dim": "#a4cddd",
    "shadow": "#000000",
    "source-color": "#273132",
    "surface": "#eefcfd",
    "surface-bright": "#eefcfd",
    "surface-container": "#e2f1f2",
    "surface-container-high": "#ddebec",
    "surface-container-highest": "#d7e5e6",
    "surface-container-low": "#e8f6f7",
    "surface-container-lowest": "#ffffff",
    "surface-dim": "#cfddde",
    "surface-tint": "#006970",
    "surface-variant": "#d7e5e6",
    "tertiary": "#316382",
    "tertiary-container": "#c8e6ff",
    "tertiary-fixed": "#c8e6ff",
    "tertiary-fixed-dim": "#9cccf0",
}

function getLightColors() {
    return lightColors;
}

function updateLightColors(newLightColors) {
    lightColors = Object.assign({}, lightColors, newLightColors);
}
